services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: productdb
    
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: backend-8upjj
    build:
      context: ./backend-8upjj
      dockerfile: backend.Dockerfile
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: frontend-8upjj
    build:
      context: ./frontend-8upjj
      dockerfile: frontend.Dockerfile
    ports:
      - "2001:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: